/*
 * Created on Mon Nov 13 2023
 *
 * Copyright (c) 2023 Your Company
 */

import { AllHTMLAttributes, SVGAttributes } from "react";

const AriaAttributes = {
  "aria-activedescendant": "aria-activedescendant",
  "aria-atomic": "aria-atomic",
  "aria-autocomplete": "aria-autocomplete",
  "aria-busy": "aria-busy",
  "aria-checked": "aria-checked",
  "aria-colcount": "aria-colcount",
  "aria-colindex": "aria-colindex",
  "aria-colspan": "aria-colspan",
  "aria-controls": "aria-controls",
  "aria-current": "aria-current",
  "aria-describedby": "aria-describedby",
  "aria-details": "aria-details",
  "aria-disabled": "aria-disabled",
  "aria-dropeffect": "aria-dropeffect",
  "aria-errormessage": "aria-errormessage",
  "aria-expanded": "aria-expanded",
  "aria-flowto": "aria-flowto",
  "aria-grabbed": "aria-grabbed",
  "aria-haspopup": "aria-haspopup",
  "aria-hidden": "aria-hidden",
  "aria-invalid": "aria-invalid",
  "aria-keyshortcuts": "aria-keyshortcuts",
  "aria-label": "aria-label",
  "aria-labelledby": "aria-labelledby",
  "aria-level": "aria-level",
  "aria-live": "aria-live",
  "aria-modal": "aria-modal",
  "aria-multiline": "aria-multiline",
  "aria-multiselectable": "aria-multiselectable",
  "aria-orientation": "aria-orientation",
  "aria-owns": "aria-owns",
  "aria-placeholder": "aria-placeholder",
  "aria-posinset": "aria-posinset",
  "aria-pressed": "aria-pressed",
  "aria-readonly": "aria-readonly",
  "aria-relevant": "aria-relevant",
  "aria-required": "aria-required",
  "aria-roledescription": "aria-roledescription",
  "aria-rowcount": "aria-rowcount",
  "aria-rowindex": "aria-rowindex",
  "aria-rowspan": "aria-rowspan",
  "aria-selected": "aria-selected",
  "aria-setsize": "aria-setsize",
  "aria-sort": "aria-sort",
  "aria-valuemax": "aria-valuemax",
  "aria-valuemin": "aria-valuemin",
  "aria-valuenow": "aria-valuenow",
  "aria-valuetext": "aria-valuetext",
};

const DOMAttributes = {
  children: "children",
  dangerouslySetInnerHTML: "dangerouslySetInnerHTML",
  onCopy: "onCopy",
  onCopyCapture: "onCopyCapture",
  onCut: "onCut",
  onCutCapture: "onCutCapture",
  onPaste: "onPaste",
  onPasteCapture: "onPasteCapture",
  onCompositionEnd: "onCompositionEnd",
  onCompositionEndCapture: "onCompositionEndCapture",
  onCompositionStart: "onCompositionStart",
  onCompositionStartCapture: "onCompositionStartCapture",
  onCompositionUpdate: "onCompositionUpdate",
  onCompositionUpdateCapture: "onCompositionUpdateCapture",
  onFocus: "onFocus",
  onFocusCapture: "onFocusCapture",
  onBlur: "onBlur",
  onBlurCapture: "onBlurCapture",
  onChange: "onChange",
  onChangeCapture: "onChangeCapture",
  onBeforeInput: "onBeforeInput",
  onBeforeInputCapture: "onBeforeInputCapture",
  onInput: "onInput",
  onInputCapture: "onInputCapture",
  onReset: "onReset",
  onResetCapture: "onResetCapture",
  onSubmit: "onSubmit",
  onSubmitCapture: "onSubmitCapture",
  onInvalid: "onInvalid",
  onInvalidCapture: "onInvalidCapture",
  onLoad: "onLoad",
  onLoadCapture: "onLoadCapture",
  onError: "onError",
  onErrorCapture: "onErrorCapture",
  onKeyDown: "onKeyDown",
  onKeyDownCapture: "onKeyDownCapture",
  onKeyPress: "onKeyPress",
  onKeyPressCapture: "onKeyPressCapture",
  onKeyUp: "onKeyUp",
  onKeyUpCapture: "onKeyUpCapture",
  onAbort: "onAbort",
  onAbortCapture: "onAbortCapture",
  onCanPlay: "onCanPlay",
  onCanPlayCapture: "onCanPlayCapture",
  onCanPlayThrough: "onCanPlayThrough",
  onCanPlayThroughCapture: "onCanPlayThroughCapture",
  onDurationChange: "onDurationChange",
  onDurationChangeCapture: "onDurationChangeCapture",
  onEmptied: "onEmptied",
  onEmptiedCapture: "onEmptiedCapture",
  onEncrypted: "onEncrypted",
  onEncryptedCapture: "onEncryptedCapture",
  onEnded: "onEnded",
  onEndedCapture: "onEndedCapture",
  onLoadedData: "onLoadedData",
  onLoadedDataCapture: "onLoadedDataCapture",
  onLoadedMetadata: "onLoadedMetadata",
  onLoadedMetadataCapture: "onLoadedMetadataCapture",
  onLoadStart: "onLoadStart",
  onLoadStartCapture: "onLoadStartCapture",
  onPause: "onPause",
  onPauseCapture: "onPauseCapture",
  onPlay: "onPlay",
  onPlayCapture: "onPlayCapture",
  onPlaying: "onPlaying",
  onPlayingCapture: "onPlayingCapture",
  onProgress: "onProgress",
  onProgressCapture: "onProgressCapture",
  onRateChange: "onRateChange",
  onRateChangeCapture: "onRateChangeCapture",
  onResize: "onResize",
  onResizeCapture: "onResizeCapture",
  onSeeked: "onSeeked",
  onSeekedCapture: "onSeekedCapture",
  onSeeking: "onSeeking",
  onSeekingCapture: "onSeekingCapture",
  onStalled: "onStalled",
  onStalledCapture: "onStalledCapture",
  onSuspend: "onSuspend",
  onSuspendCapture: "onSuspendCapture",
  onTimeUpdate: "onTimeUpdate",
  onTimeUpdateCapture: "onTimeUpdateCapture",
  onVolumeChange: "onVolumeChange",
  onVolumeChangeCapture: "onVolumeChangeCapture",
  onWaiting: "onWaiting",
  onWaitingCapture: "onWaitingCapture",

  // MouseEvents
  onAuxClick: "onAuxClick",
  onAuxClickCapture: "onAuxClickCapture",
  onClick: "onClick",
  onClickCapture: "onClickCapture",
  onContextMenu: "onContextMenu",
  onContextMenuCapture: "onContextMenuCapture",
  onDoubleClick: "onDoubleClick",
  onDoubleClickCapture: "onDoubleClickCapture",
  onDrag: "onDrag",
  onDragCapture: "onDragCapture",
  onDragEnd: "onDragEnd",
  onDragEndCapture: "onDragEndCapture",
  onDragEnter: "onDragEnter",
  onDragEnterCapture: "onDragEnterCapture",
  onDragExit: "onDragExit",
  onDragExitCapture: "onDragExitCapture",
  onDragLeave: "onDragLeave",
  onDragLeaveCapture: "onDragLeaveCapture",
  onDragOver: "onDragOver",
  onDragOverCapture: "onDragOverCapture",
  onDragStart: "onDragStart",
  onDragStartCapture: "onDragStartCapture",
  onDrop: "onDrop",
  onDropCapture: "onDropCapture",
  onMouseDown: "onMouseDown",
  onMouseDownCapture: "onMouseDownCapture",
  onMouseEnter: "onMouseEnter",
  onMouseLeave: "onMouseLeave",
  onMouseMove: "onMouseMove",
  onMouseMoveCapture: "onMouseMoveCapture",
  onMouseOut: "onMouseOut",
  onMouseOutCapture: "onMouseOutCapture",
  onMouseOver: "onMouseOver",
  onMouseOverCapture: "onMouseOverCapture",
  onMouseUp: "onMouseUp",
  onMouseUpCapture: "onMouseUpCapture",

  // Selection Events
  onSelect: "onSelect",
  onSelectCapture: "onSelectCapture",

  // Touch Events
  onTouchCancel: "onTouchCancel",
  onTouchCancelCapture: "onTouchCancelCapture",
  onTouchEnd: "onTouchEnd",
  onTouchEndCapture: "onTouchEndCapture",
  onTouchMove: "onTouchMove",
  onTouchMoveCapture: "onTouchMoveCapture",
  onTouchStart: "onTouchStart",
  onTouchStartCapture: "onTouchStartCapture",

  // Pointer Events
  onPointerDown: "onPointerDown",
  onPointerDownCapture: "onPointerDownCapture",
  onPointerMove: "onPointerMove",
  onPointerMoveCapture: "onPointerMoveCapture",
  onPointerUp: "onPointerUp",
  onPointerUpCapture: "onPointerUpCapture",
  onPointerCancel: "onPointerCancel",
  onPointerCancelCapture: "onPointerCancelCapture",
  onPointerEnter: "onPointerEnter",
  onPointerEnterCapture: "onPointerEnterCapture",
  onPointerLeave: "onPointerLeave",
  onPointerLeaveCapture: "onPointerLeaveCapture",
  onPointerOver: "onPointerOver",
  onPointerOverCapture: "onPointerOverCapture",
  onPointerOut: "onPointerOut",
  onPointerOutCapture: "onPointerOutCapture",
  onGotPointerCapture: "onGotPointerCapture",
  onGotPointerCaptureCapture: "onGotPointerCaptureCapture",
  onLostPointerCapture: "onLostPointerCapture",
  onLostPointerCaptureCapture: "onLostPointerCaptureCapture",

  // UI Events
  onScroll: "onScroll",
  onScrollCapture: "onScrollCapture",

  // Wheel Events
  onWheel: "onWheel",
  onWheelCapture: "onWheelCapture",

  // Animation Events
  onAnimationStart: "onAnimationStart",
  onAnimationStartCapture: "onAnimationStartCapture",
  onAnimationEnd: "onAnimationEnd",
  onAnimationEndCapture: "onAnimationEndCapture",
  onAnimationIteration: "onAnimationIteration",
  onAnimationIterationCapture: "onAnimationIterationCapture",

  // Transition Events
  onTransitionEnd: "onTransitionEnd",
  onTransitionEndCapture: "onTransitionEndCapture",
};

const SVGAttrs: { [key: string]: string } = {
  suppressHydrationWarning: "suppressHydrationWarning",

  className: "className",
  color: "color",
  height: "height",
  id: "id",
  lang: "lang",
  max: "max",
  media: "media",
  method: "method",
  min: "min",
  name: "name",
  style: "style",
  target: "target",
  type: "type",
  width: "width",

  // Other HTML properties supported by SVG elements in browsers
  role: "role",
  tabIndex: "tabIndex",
  crossOrigin: "crossOrigin",

  // SVG Specific attributes
  accentHeight: "accentHeight",
  accumulate: "accumulate",
  additive: "additive",
  alignmentBaseline: "alignmentBaseline",
  allowReorder: "allowReorder",
  alphabetic: "alphabetic",
  amplitude: "amplitude",
  arabicForm: "arabicForm",
  ascent: "ascent",
  attributeName: "attributeName",
  attributeType: "attributeType",
  autoReverse: "autoReverse",
  azimuth: "azimuth",
  baseFrequency: "baseFrequency",
  baselineShift: "baselineShift",
  baseProfile: "baseProfile",
  bbox: "bbox",
  begin: "begin",
  bias: "bias",
  by: "by",
  calcMode: "calcMode",
  capHeight: "capHeight",
  clip: "clip",
  clipPath: "clipPath",
  clipPathUnits: "clipPathUnits",
  clipRule: "clipRule",
  colorInterpolation: "colorInterpolation",
  colorInterpolationFilters: "colorInterpolationFilters",
  colorProfile: "colorProfile",
  colorRendering: "colorRendering",
  contentScriptType: "contentScriptType",
  contentStyleType: "contentStyleType",
  cursor: "cursor",
  cx: "cx",
  cy: "cy",
  d: "d",
  decelerate: "decelerate",
  descent: "descent",
  diffuseConstant: "diffuseConstant",
  direction: "direction",
  display: "display",
  divisor: "divisor",
  dominantBaseline: "dominantBaseline",
  dur: "dur",
  dx: "dx",
  dy: "dy",
  edgeMode: "edgeMode",
  elevation: "elevation",
  enableBackground: "enableBackground",
  end: "end",
  exponent: "exponent",
  externalResourcesRequired: "externalResourcesRequired",
  fill: "fill",
  fillOpacity: "fillOpacity",
  fillRule: "fillRule",
  filter: "filter",
  filterRes: "filterRes",
  filterUnits: "filterUnits",
  floodColor: "floodColor",
  floodOpacity: "floodOpacity",
  focusable: "focusable",
  fontFamily: "fontFamily",
  fontSize: "fontSize",
  fontSizeAdjust: "fontSizeAdjust",
  fontStretch: "fontStretch",
  fontStyle: "fontStyle",
  fontVariant: "fontVariant",
  fontWeight: "fontWeight",
  format: "format",
  fr: "fr",
  from: "from",
  fx: "fx",
  fy: "fy",
  g1: "g1",
  g2: "g2",
  glyphName: "glyphName",
  glyphOrientationHorizontal: "glyphOrientationHorizontal",
  glyphOrientationVertical: "glyphOrientationVertical",
  glyphRef: "glyphRef",
  gradientTransform: "gradientTransform",
  gradientUnits: "gradientUnits",
  hanging: "hanging",
  horizAdvX: "horizAdvX",
  horizOriginX: "horizOriginX",
  href: "href",
  ideographic: "ideographic",
  imageRendering: "imageRendering",
  in2: "in2",
  in: "in",
  intercept: "intercept",
  k1: "k1",
  k2: "k2",
  k3: "k3",
  k4: "k4",
  k: "k",
  kernelMatrix: "kernelMatrix",
  kernelUnitLength: "kernelUnitLength",
  kerning: "kerning",
  keyPoints: "keyPoints",
  keySplines: "keySplines",
  keyTimes: "keyTimes",
  lengthAdjust: "lengthAdjust",
  letterSpacing: "letterSpacing",
  lightingColor: "lightingColor",
  limitingConeAngle: "limitingConeAngle",
  local: "local",
  markerEnd: "markerEnd",
  markerHeight: "markerHeight",
  markerMid: "markerMid",
  markerStart: "markerStart",
  markerUnits: "markerUnits",
  markerWidth: "markerWidth",
  mask: "mask",
  maskContentUnits: "maskContentUnits",
  maskUnits: "maskUnits",
  mathematical: "mathematical",
  mode: "mode",
  numOctaves: "numOctaves",
  offset: "offset",
  opacity: "opacity",
  operator: "operator",
  order: "order",
  orient: "orient",
  orientation: "orientation",
  origin: "origin",
  overflow: "overflow",
  overlinePosition: "overlinePosition",
  overlineThickness: "overlineThickness",
  paintOrder: "paintOrder",
  panose1: "panose1",
  path: "path",
  pathLength: "pathLength",
  patternContentUnits: "patternContentUnits",
  patternTransform: "patternTransform",
  patternUnits: "patternUnits",
  pointerEvents: "pointerEvents",
  points: "points",
  pointsAtX: "pointsAtX",
  pointsAtY: "pointsAtY",
  pointsAtZ: "pointsAtZ",
  preserveAlpha: "preserveAlpha",
  preserveAspectRatio: "preserveAspectRatio",
  primitiveUnits: "primitiveUnits",
  r: "r",
  radius: "radius",
  refX: "refX",
  refY: "refY",
  renderingIntent: "renderingIntent",
  repeatCount: "repeatCount",
  repeatDur: "repeatDur",
  requiredExtensions: "requiredExtensions",
  requiredFeatures: "requiredFeatures",
  restart: "restart",
  result: "result",
  rotate: "rotate",
  rx: "rx",
  ry: "ry",
  scale: "scale",
  seed: "seed",
  shapeRendering: "shapeRendering",
  slope: "slope",
  spacing: "spacing",
  specularConstant: "specularConstant",
  specularExponent: "specularExponent",
  speed: "speed",
  spreadMethod: "spreadMethod",
  startOffset: "startOffset",
  stdDeviation: "stdDeviation",
  stemh: "stemh",
  stemv: "stemv",
  stitchTiles: "stitchTiles",
  stopColor: "stopColor",
  stopOpacity: "stopOpacity",
  strikethroughPosition: "strikethroughPosition",
  strikethroughThickness: "strikethroughThickness",
  string: "string",
  stroke: "stroke",
  strokeDasharray: "strokeDasharray",
  strokeDashoffset: "strokeDashoffset",
  strokeLinecap: "strokeLinecap",
  strokeLinejoin: "strokeLinejoin",
  strokeMiterlimit: "strokeMiterlimit",
  strokeOpacity: "strokeOpacity",
  strokeWidth: "strokeWidth",
  surfaceScale: "surfaceScale",
  systemLanguage: "systemLanguage",
  tableValues: "tableValues",
  targetX: "targetX",
  targetY: "targetY",
  textAnchor: "textAnchor",
  textDecoration: "textDecoration",
  textLength: "textLength",
  textRendering: "textRendering",
  to: "to",
  transform: "transform",
  u1: "u1",
  u2: "u2",
  underlinePosition: "underlinePosition",
  underlineThickness: "underlineThickness",
  unicode: "unicode",
  unicodeBidi: "unicodeBidi",
  unicodeRange: "unicodeRange",
  unitsPerEm: "unitsPerEm",
  vAlphabetic: "vAlphabetic",
  values: "values",
  vectorEffect: "vectorEffect",
  version: "version",
  vertAdvY: "vertAdvY",
  vertOriginX: "vertOriginX",
  vertOriginY: "vertOriginY",
  vHanging: "vHanging",
  vIdeographic: "vIdeographic",
  viewBox: "viewBox",
  viewTarget: "viewTarget",
  visibility: "visibility",
  vMathematical: "vMathematical",
  widths: "widths",
  wordSpacing: "wordSpacing",
  writingMode: "writingMode",
  x1: "x1",
  x2: "x2",
  x: "x",
  xChannelSelector: "xChannelSelector",
  xHeight: "xHeight",
  xlinkActuate: "xlinkActuate",
  xlinkArcrole: "xlinkArcrole",
  xlinkHref: "xlinkHref",
  xlinkRole: "xlinkRole",
  xlinkShow: "xlinkShow",
  xlinkTitle: "xlinkTitle",
  xlinkType: "xlinkType",
  xmlBase: "xmlBase",
  xmlLang: "xmlLang",
  xmlns: "xmlns",
  xmlnsXlink: "xmlnsXlink",
  xmlSpace: "xmlSpace",
  y1: "y1",
  y2: "y2",
  y: "y",
  yChannelSelector: "yChannelSelector",
  z: "z",
  zoomAndPan: "zoomAndPan",
  ...AriaAttributes,
  ...DOMAttributes,
};

const HTMLAttrs: { [key: string]: string } = {
  accept: "accept",
  acceptCharset: "acceptCharset",
  action: "action",
  allowFullScreen: "allowFullScreen",
  allowTransparency: "allowTransparency",
  alt: "alt",
  as: "as",
  async: "async",
  autoComplete: "autoComplete",
  autoPlay: "autoPlay",
  capture: "capture",
  cellPadding: "cellPadding",
  cellSpacing: "cellSpacing",
  charSet: "charSet",
  challenge: "challenge",
  checked: "checked",
  cite: "cite",
  classID: "classID",
  cols: "cols",
  colSpan: "colSpan",
  content: "content",
  controls: "controls",
  coords: "coords",
  crossOrigin: "crossOrigin",
  data: "data",
  dateTime: "dateTime",
  default: "default",
  defer: "defer",
  disabled: "disabled",
  download: "download",
  encType: "encType",
  form: "form",
  formAction: "formAction",
  formEncType: "formEncType",
  formMethod: "formMethod",
  formNoValidate: "formNoValidate",
  formTarget: "formTarget",
  frameBorder: "frameBorder",
  headers: "headers",
  height: "height",
  high: "high",
  href: "href",
  hrefLang: "hrefLang",
  htmlFor: "htmlFor",
  httpEquiv: "httpEquiv",
  integrity: "integrity",
  keyParams: "keyParams",
  keyType: "keyType",
  kind: "kind",
  label: "label",
  list: "list",
  loop: "loop",
  low: "low",
  manifest: "manifest",
  marginHeight: "marginHeight",
  marginWidth: "marginWidth",
  max: "max",
  maxLength: "maxLength",
  media: "media",
  mediaGroup: "mediaGroup",
  method: "method",
  min: "min",
  minLength: "minLength",
  multiple: "multiple",
  muted: "muted",
  name: "name",
  noValidate: "noValidate",
  open: "open",
  optimum: "optimum",
  pattern: "pattern",
  placeholder: "placeholder",
  playsInline: "playsInline",
  poster: "poster",
  preload: "preload",
  readOnly: "readOnly",
  rel: "rel",
  required: "required",
  reversed: "reversed",
  rows: "rows",
  rowSpan: "rowSpan",
  sandbox: "sandbox",
  scope: "scope",
  scoped: "scoped",
  scrolling: "scrolling",
  seamless: "seamless",
  selected: "selected",
  shape: "shape",
  size: "size",
  sizes: "sizes",
  span: "span",
  src: "src",
  srcDoc: "srcDoc",
  srcLang: "srcLang",
  srcSet: "srcSet",
  start: "start",
  step: "step",
  summary: "summary",
  target: "target",
  type: "type",
  useMap: "useMap",
  value: "value",
  width: "width",
  wmode: "wmode",
  wrap: "wrap",

  defaultChecked: "defaultChecked",
  defaultValue: "defaultValue",
  suppressContentEditableWarning: "suppressContentEditableWarning",
  suppressHydrationWarning: "suppressHydrationWarning",

  // Standard HTML Attributes
  accessKey: "accessKey",
  autoFocus: "autoFocus",
  className: "className",
  contentEditable: "contentEditable",
  contextMenu: "contextMenu",
  dir: "dir",
  draggable: "draggable",
  hidden: "hidden",
  id: "id",
  lang: "lang",
  nonce: "nonce",
  slot: "slot",
  spellCheck: "spellCheck",
  style: "style",
  tabIndex: "tabIndex",
  title: "title",
  translate: "translate",

  // Unknown
  radioGroup: "radioGroup",

  // WAI-ARIA
  role: "role",

  // RDFa Attributes
  about: "about",
  datatype: "datatype",
  inlist: "inlist",
  prefix: "prefix",
  property: "property",
  resource: "resource",
  typeof: "typeof",
  vocab: "vocab",

  // Non-standard Attributes
  autoCapitalize: "autoCapitalize",
  autoCorrect: "autoCorrect",
  autoSave: "autoSave",
  color: "color",
  itemProp: "itemProp",
  itemScope: "itemScope",
  itemType: "itemType",
  itemID: "itemID",
  itemRef: "itemRef",
  results: "results",
  security: "security",
  unselectable: "unselectable",
  inputMode: "inputMode",
  is: "is",

  ...AriaAttributes,

  ...DOMAttributes,
};

function checkDataSet(attrs: string) {
  const regex = /^data-/;
  return regex.test(attrs);
}

/**
 *  Row, Column, Grid를 사용하는 곳에서
 *  HTMLAttributes를 제외한 custom props가 boolean 혹은 camelCase일 경우 콘솔 에러가 발생하기 때문에,
 *  custom props를 필터링 처리하기 위한 임시 방편 코드입니다.
 * 	후에 이 에러를 해결하기 위한 다른 방법이 생기면 대체해야합니다.
 *
 * 	@param props 모든 props 객체
 * 	@return HTMLAttribute만 남고 나머지는 필터링된 객체
 */
export function filterHTMLAttribute<T>(
  props: AllHTMLAttributes<HTMLElement> & T
) {
  const result = { ...props };

  Object.keys(result).forEach((attr) => {
    if (!HTMLAttrs[attr] && !checkDataSet(attr)) {
      //@ts-ignore
      delete result[attr];
    }
  });

  return result;
}

export function filterSVGAttribute<T>(props: SVGAttributes<SVGElement> & T) {
  const result = { ...props };

  Object.keys(result).forEach((attr) => {
    if (!SVGAttrs[attr] && !checkDataSet(attr)) {
      //@ts-ignore
      delete result[attr];
    }
  });

  return result;
}

export function filterHTMLDataAttribute<T>(
  props: AllHTMLAttributes<HTMLElement> & T
) {
  const result = { ...props };

  Object.keys(result).forEach((attr) => {
    if (!checkDataSet(attr)) {
      //@ts-ignore
      delete result[attr];
    }
  });

  return result;
}
