import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Row } from "@/components";
import { useRouter } from "next/router";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const handleRoute = (ev: React.MouseEvent<HTMLButtonElement>) => {
    const target = ev.target as HTMLButtonElement;
    const id = target.id;

    switch (id) {
      case "sign-in": {
        router.push("login");
        break;
      }
      case "sign-up": {
        router.push("sign-up");
        break;
      }
      case "infinity-board": {
        router.push("board/infinity");
        break;
      }
      case "pagination-board": {
        router.push("board/pagination");
        break;
      }
      case "club": {
        router.push("club/1?tab=home");
        break;
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <button
            role="button"
            onClick={(ev) => {
              throw Error("에러!");
            }}
          >
            에러
          </button>
          <Row.ul css={{ width: "100%" }} gap={10} horizonAlign="center">
            <Row.li>
              <button id="sign-in" onClick={handleRoute}>
                로그인
              </button>
            </Row.li>
            <Row.li>
              <button id="sign-up" onClick={handleRoute}>
                회원가입
              </button>
            </Row.li>
            <Row.li>
              <button id="infinity-board" onClick={handleRoute}>
                무한스크롤 게시판
              </button>
            </Row.li>
            <Row.li>
              <button id="pagination-board" onClick={handleRoute}>
                페이지네이션 게시판
              </button>
            </Row.li>
            <Row.li>
              <button id="club" onClick={handleRoute}>
                동아리
              </button>
            </Row.li>
          </Row.ul>
        </div>
      </main>
    </>
  );
}
