import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Row } from "@/components/Row";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Row.ul gap={4}>
            <Row.li>1</Row.li>
            <Row.li>2</Row.li>
            <Row.li>3</Row.li>
            <Row.li>4</Row.li>
            <Row.li>5</Row.li>
          </Row.ul>
        </div>
      </main>
    </>
  );
}
